# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build the application

on:
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test, lint, build and audit the app
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run npm audit
        run: npm audit
      - name: Lint the application
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Build typescript
        run: npm run build
    env:
      CI: true

  build-docker-image:
    needs: [test]
    runs-on: [ubuntu-latest]
    name: Build docker image
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: docker build -t "wpaczula/ts-node-boilerplate:$IMAGE_TAG" .
      - name: Finish
        run: echo Image will be automatically built on dockerhub
